apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout-api
  namespace: apps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: checkout-api
  template:
    metadata:
      labels:
        app: checkout-api
    spec:
      containers:
        - name: checkout
          image: hashicorp/http-echo
          args:
            - "-text=checkout response"
          env:
            - name: PAYMENT_URL
              value: http://payment-api.apps.svc.cluster.local
            - name: REDIS_HOST
              value: redis.apps.svc.cluster.local
          ports:
            - containerPort: 5678
